# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_flexible_ocr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentFaceRecorder(object):
    def setupUi(self, StudentFaceRecorder):
        StudentFaceRecorder.setObjectName("StudentFaceRecorder")
        StudentFaceRecorder.resize(1038, 601)
        self.centralwidget = QtWidgets.QWidget(StudentFaceRecorder)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(5000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 3, 1, 1, 1)
        self.video_label = QtWidgets.QLabel(self.centralwidget)
        self.video_label.setMinimumSize(QtCore.QSize(800, 600))
        self.video_label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")
        self.gridLayout_3.addWidget(self.video_label, 0, 1, 3, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"font: 16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(354, 65))
        self.label_3.setStyleSheet("font: 75 16pt  \"Bahnschrift Condensed\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 3, 1)
        StudentFaceRecorder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StudentFaceRecorder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 22))
        self.menubar.setObjectName("menubar")
        StudentFaceRecorder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StudentFaceRecorder)
        self.statusbar.setObjectName("statusbar")
        StudentFaceRecorder.setStatusBar(self.statusbar)

        self.retranslateUi(StudentFaceRecorder)
        QtCore.QMetaObject.connectSlotsByName(StudentFaceRecorder)

    def retranslateUi(self, StudentFaceRecorder):
        _translate = QtCore.QCoreApplication.translate
        StudentFaceRecorder.setWindowTitle(_translate("StudentFaceRecorder", "MainWindow"))
        self.label.setText(_translate("StudentFaceRecorder", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Recognition System</span></p></body></html>"))
        self.pushButton_3.setText(_translate("StudentFaceRecorder", "Start"))
        self.pushButton_2.setText(_translate("StudentFaceRecorder", "Stop"))
        self.pushButton.setText(_translate("StudentFaceRecorder", "Exit"))
        self.label_2.setText(_translate("StudentFaceRecorder", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("StudentFaceRecorder", "<html><head/><body><p align=\"center\">Please remain in front of the camera for 5 seconds</p></body></html>"))
