# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_flexible_ocr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentFaceRecorder(object):
    def setupUi(self, StudentFaceRecorder):
        StudentFaceRecorder.setObjectName("StudentFaceRecorder")
        StudentFaceRecorder.resize(852, 616)
        self.centralwidget = QtWidgets.QWidget(StudentFaceRecorder)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 841, 61))
        self.label.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"font: 16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 841, 991))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(90, 460, 681, 61))
        self.frame_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 400, 421, 51))
        self.label_2.setStyleSheet("font: 75 16pt \"Microsoft JhengHei UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 520, 841, 41))
        self.label_3.setStyleSheet("font: 75 16pt \"Microsoft JhengHei UI\";")
        self.label_3.setObjectName("label_3")
        self.frame.raise_()
        self.label.raise_()
        StudentFaceRecorder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StudentFaceRecorder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        StudentFaceRecorder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StudentFaceRecorder)
        self.statusbar.setObjectName("statusbar")
        StudentFaceRecorder.setStatusBar(self.statusbar)

        self.retranslateUi(StudentFaceRecorder)
        QtCore.QMetaObject.connectSlotsByName(StudentFaceRecorder)

    def retranslateUi(self, StudentFaceRecorder):
        _translate = QtCore.QCoreApplication.translate
        StudentFaceRecorder.setWindowTitle(_translate("StudentFaceRecorder", "MainWindow"))
        self.label.setText(_translate("StudentFaceRecorder", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Recognition System</span></p></body></html>"))
        self.pushButton_3.setText(_translate("StudentFaceRecorder", "Start"))
        self.pushButton_2.setText(_translate("StudentFaceRecorder", "Stop"))
        self.pushButton.setText(_translate("StudentFaceRecorder", "Exit"))
        self.label_2.setText(_translate("StudentFaceRecorder", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("StudentFaceRecorder", "<html><head/><body><p align=\"center\">Please remain still in front of the camera for 5 seconds</p></body></html>"))
